/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Barcode
 #	author : miyako
 #	2012/11/25
 #
 # --------------------------------------------------------------------------------*/



// --- qrencode
void MICRO_QRCODE_Data(sLONG_PTR *pResult, PackagePtr pParams);
void MICRO_QRCODE_Text(sLONG_PTR *pResult, PackagePtr pParams);
void QRCODE_Data(sLONG_PTR *pResult, PackagePtr pParams);
void QRCODE_Text(sLONG_PTR *pResult, PackagePtr pParams);

